### ISSUE TITLE
Failing Listeners Cause Execution to Stop

### ISSUE THREAD

**Issue by mroeder** [pdubroy/checked-emitter#3]
When adding a listener that throws an error, the listeners following after the failed listener are not triggered `(#1)`. Moreover, the the error bubbles to the point where `emit()` was executed and interrupts the outer program flow too `(#2)`.

Test case:
```javascript
test('failing listeners', t => {
  let e = new CheckedEmitter();
  let x = false;
  let y = false;

  e.registerEvent('trigger');
  e.addListener('trigger', () => { throw new Error(); x = true; });
  e.addListener('trigger', () => { y = true; });
  e.emit('trigger'); // (#2) should continue and not stop here

  t.equal(x, false, 'x was not changed');
  t.equal(y, true, 'y was changed'); // (#1) should reach the second listener

  t.end();
});
```

**Comment by pdubroy** [comment]
Is this different from how fbemitter behaves?

**Comment by pdubroy** [comment]
It seems that fbemitter has the same behaviour:

```
> const fbemitter = require('fbemitter');
undefined
> const e = new fbemitter.EventEmitter();
undefined
> e.addListener('foo', () => { throw new Error('oops'); })
> (function() { e.emit('foo'); console.log('made it!'); })()
Error: oops
    at e.addListener (repl:1:36)
    at BaseEventEmitter.__emitToSubscription (/private/tmp/node_modules/fbemitter/lib/BaseEventEmitter.js:185:27)
    at BaseEventEmitter.emit (/private/tmp/node_modules/fbemitter/lib/BaseEventEmitter.js:166:37)
    at repl:1:17
    at repl:1:57
    at REPLServer.defaultEval (repl.js:272:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:441:10)
    at emitOne (events.js:101:20)
```

I'm tempted to leave it this way, as I'm not sure I want to go down the road of trying to improve on their API -- I'd rather just keep this a naive wrapper.

Do you have a particular use case where you think it should really catch the error? You can always wrap your own handlers with try/catch so it seems more flexible the way it is.

**Comment by mroeder** [comment]
I think it's reasonable to think that an event system should not break just because one of the listeners has a problem. It doesn't happen to DOM events for example:

``` javascript
var event = new Event('testEvent');
var x = false;
var y = false;

// var elem = document.query(...);
elem.addEventListener('testEvent', function (e) { throw new Error(); x = true; });
elem.addEventListener('testEvent', function (e) { y = true; });

elem.dispatchEvent(event);

x === true; // false
y === true; // true
```

Current use-case - and where I discovered the problem - is the Ohm Editor and different prototypes registering to `parse:grammar`. If some prototype fails, my listener won't get called (and I don't want to fix other things first before being able to do my work).

**Comment by pdubroy** [comment]
I don't know, I'm tempted to leave this as is. First, because I'd like to keep this package an as-simple-as-possible wrapper about fbemitter, and second, because I think fail-fast is probably a better default behaviour.
